app.Actions = {

    RECEIVE_RAW_TICKETS: "RECEIVE_RAW_TICKETS",
    NEW_TICKET_CREATED: "NEW_TICKET_CREATED"

};

app.PayloadSources = {

    SERVER_ACTION: 'SERVER_ACTION',
    VIEW_ACTION: 'VIEW_ACTION'

};